name = "MC1.18.2"
author = "TN_TechNoob"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7edca837333f7662d9e0a8ec3d0e67c9d8da621f52b553d3c50e4be7632de268"

[versions]
fabric = "0.16.9"
minecraft = "1.18.2"
